TruckCompany.Web/Controllers/TruckerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TruckCompany.Web.Models;
using TruckCompany.DataAccess;

namespace TruckCompany.Web.Controllers
{
    public class TruckerController : Controller 
    {
        private readonly TruckCompanyDBContext _dBContext;
        public TruckerController(TruckCompanyDBContext dBContext)
        {
            _dBContext = dBContext;
        }
        // GET: TruckerController
        public ActionResult Index()
        {
            IEnumerable<DomainEntities.Trucker> data = _dBContext.Truckers;
            return View(data.Select(x => new TruckerModel(x))) ;
        }

        // GET: TruckerController/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            DomainEntities.Trucker obj = _dBContext.Truckers.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(new TruckerModel(obj));
        }

        // GET: TruckerController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: TruckerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DomainEntities.Trucker obj)
        {
            _dBContext.Truckers.Add(obj);
            _dBContext.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: TruckerController/Edit/5
        public ActionResult Update(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            DomainEntities.Trucker obj = _dBContext.Truckers.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(new TruckerModel(obj));
        }

        // POST: TruckerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(DomainEntities.Trucker obj)
        {
            _dBContext.Truckers.Update(obj);
            _dBContext.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: TruckerController/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            DomainEntities.Trucker obj = _dBContext.Truckers.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(new TruckerModel(obj));
        }

        // POST: TruckerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(Guid? id)
        {
            DomainEntities.Trucker obj = _dBContext.Truckers.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            IEnumerable<DomainEntities.AssignRoute> routes = _dBContext.AssignedRoutes;
            foreach(var item in routes)
            {
                if (item.TruckerId == obj.Id)
                {
                    _dBContext.AssignedRoutes.Remove(item);
                }
            }
            _dBContext.Truckers.Remove(obj);
            _dBContext.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

TruckCompany.Web/Views/Trucker/Create.cshtml
@model TruckCompany.Web.Models.TruckerModel


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Trucker</h4>
<hr />

<div class="row">
    <div class="col-md-4 text-center"s>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
    
<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

TruckCompany.Web/Views/Trucker/Delete.cshtml
@model TruckCompany.DomainEntities.Trucker

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trucker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="DeletePost">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TruckCompany.Web/Views/Trucker/Details.cshtml
@model TruckerModel

@{
    ViewData["Title"] = "Details";
}

<h1>Trucker Details</h1>

<div >
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>

    <form asp-action="Details">
        <input type="hidden" asp-for="Id" />
        <a asp-action="Index" class="btn btn-dark">Back to List</a>
    </form>
</div>

TruckCompany.Web/Views/Trucker/Index.cshtml
@model IEnumerable<TruckerModel>

    <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/v4-shims.css">
    </head>
    <body>


        <div class="container p-3">

            <div class="row pt-4">
                <div class="col-6">
                    <h2 class="text-primary">Truckers List</h2>
                </div>
                <div class="col-6 text-right">
                    <a asp-controller="Trucker" asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i>&nbsp;Add new Trucker</a>
                </div>
                <br /><br />
                @if (Model.Count() > 0)
                {
                    <table class="table table-bordered table-striped" style="width:100%">
                        <thead>
                            <tr>
                                <th>
                                    FirstName
                                </th>
                                <th>
                                    LastName
                                </th>
                                <th>
                                    PhoneNumber
                                </th>
                                <th>
                                    Actions
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td width="30%">@item.FirstName</td>
                                    <td width="30%">@item.LastName</td>
                                    <td width="30%">@item.PhoneNumber</td>
                                    <td width="50%">
                                        <div class="col-6 text-right">
                                            <a asp-controller="Trucker" asp-action="Details" asp-route-Id="@item.Id" class="btn btn-info"><i class="fas fa-info"></i></a>
                                            <a asp-controller="Trucker" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-primary"><i class="fas fa-user-edit"></i></a>
                                            <a asp-controller="Trucker" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger"><i class="fas fa-user-times"></i></a>
                                        </div>
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </body>

TruckCompany.Web/Views/Trucker/Update.cshtml
@model TruckerModel

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Trucker</h4>
<hr />
<div class="row">
    <div class="col-md-4 align-center">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>