TruckCompany.Web/Models/RouteView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TruckCompany.Web.Models
{
    public class RouteView
    {
        public RouteView(int rn,string tn,string ln,string sn)
        {
            RouteNumber = rn;
            TruckerName = tn;
            LocationName = ln;
            StatusName = sn;
        }
        public int RouteNumber { get; set; }
        public string TruckerName { get; set; }
        public string LocationName { get; set; }

        public string StatusName { get; set; }
    }
}

TruckCompany.Web/Controllers/RoutesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TruckCompany.DataAccess;
using TruckCompany.Web.Models;

namespace TruckCompany.Web.Controllers
{
    public class RoutesController : Controller
    {
        private static TruckCompanyDBContext _dBContext;

        public RoutesController(TruckCompanyDBContext dBContext)
        {
            _dBContext = dBContext;
        }
        // GET: RoutesController
        public ActionResult Index()
        {
            IEnumerable<DomainEntities.AssignRoute> data = _dBContext.AssignedRoutes;
            List<RouteView> views = new List<RouteView>();
            foreach (var item in data)
             {
                _dBContext = new TruckCompanyDBContext();
                var objT= _dBContext.Truckers.Single(a => a.Id == item.TruckerId);
                _dBContext = new TruckCompanyDBContext();
                 var objL = _dBContext.Locations.Single(a => a.Id == item.LocationId);
                _dBContext = new TruckCompanyDBContext();
                var objS = _dBContext.Statuses.Single(a => a.Id == item.StatusId);
                RouteView routeView = new RouteView(item.RouteNumber, objT.FirstName + " " + objT.LastName, objL.Name, objS.Name);
                views.Add(routeView);
            }

            return View(views);
        }

        // GET: RoutesController/Details/5
        public ActionResult Details(int id)
        {
            DomainEntities.AssignRoute obj = _dBContext.AssignedRoutes.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _dBContext = new TruckCompanyDBContext();
            var objT = _dBContext.Truckers.Single(a => a.Id == obj.TruckerId);
            _dBContext = new TruckCompanyDBContext();
            var objL = _dBContext.Locations.Single(a => a.Id == obj.LocationId);
            _dBContext = new TruckCompanyDBContext();
            var objS = _dBContext.Statuses.Single(a => a.Id == obj.StatusId);
            return View(new RouteView(id, objT.FirstName + " " + objT.LastName, objL.Name, objS.Name));
        }

        // GET: RoutesController/Create
        public ActionResult Create()
        {
            IEnumerable<DomainEntities.Trucker> truckers = _dBContext.Truckers;
            IEnumerable<DomainEntities.Status> statuses = _dBContext.Statuses;
            IEnumerable<DomainEntities.Location> locations = _dBContext.Locations;
            RouteModel route=new RouteModel();
            CreateModel createModel = new CreateModel
            {
                Route = route,
                Truckers = truckers,
                Locations = locations,
                Statuses = statuses
            };
            return View(createModel);
        }

        // POST: RoutesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DomainEntities.AssignRoute routes)
        {
            string val=Request.Form["TruckerId"];
            Guid tId = Guid.Parse(val);
            val = Request.Form["LocationId"];
            int lId = Int32.Parse(val);
            val = Request.Form["StatusId"];
            int sId = Int32.Parse(val);
            routes.TruckerId = tId;
            routes.LocationId = lId;
            routes.StatusId = sId;
           _dBContext.AssignedRoutes.Add(routes);
            //_dBContext.AssignedRoutes.AddAsync(routes);
            _dBContext.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: RoutesController/Edit/5
        public ActionResult Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            DomainEntities.AssignRoute obj = _dBContext.AssignedRoutes.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            IEnumerable<DomainEntities.Trucker> truckers = _dBContext.Truckers;
            IEnumerable<DomainEntities.Status> statuses = _dBContext.Statuses;
            IEnumerable<DomainEntities.Location> locations = _dBContext.Locations;
            CreateModel createModel = new CreateModel
            {
                Route = new RouteModel(obj),
                Truckers = truckers,
                Locations = locations,
                Statuses = statuses
            };
            return View(createModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(int id)
        {
           
            string val = Request.Form["TruckerId"];
            Guid tId = Guid.Parse(val);
            val = Request.Form["LocationId"];
            int lId = Int32.Parse(val);
            val = Request.Form["StatusId"];
            int sId = Int32.Parse(val);
            DomainEntities.AssignRoute routes = new DomainEntities.AssignRoute
            {
                RouteNumber=id,
                TruckerId=tId,
                LocationId=lId,
                StatusId=sId
            };
            _dBContext.AssignedRoutes.Update(routes);
            _dBContext.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: RoutesController/Delete/5
        public ActionResult Delete(int id)
        {
            DomainEntities.AssignRoute obj = _dBContext.AssignedRoutes.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _dBContext = new TruckCompanyDBContext();
            var objT = _dBContext.Truckers.Single(a => a.Id == obj.TruckerId);
            _dBContext = new TruckCompanyDBContext();
            var objL = _dBContext.Locations.Single(a => a.Id == obj.LocationId);
            _dBContext = new TruckCompanyDBContext();
            var objS = _dBContext.Statuses.Single(a => a.Id == obj.StatusId);
            return View(new RouteView(id,objT.FirstName+" "+objT.LastName,objL.Name,objS.Name));
        }

        // POST: TruckerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int? id)
        {
            string s = Request.Form["DeleteId"];
            id = Int32.Parse(s);
            if (id == null)
                return NotFound();
            DomainEntities.AssignRoute route = _dBContext.AssignedRoutes.Find(id);
            if (route == null)
            {
                return NotFound();
            }
            _dBContext.AssignedRoutes.Remove(route);
            _dBContext.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

TruckCompany.Web/Views/Routes/Create.cshtml
@model CreateModel

@{
    ViewData["Title"] = "Create";
}
<h1>Create</h1>

<h4>Route</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <table class="table table-bordered table-striped" style="width:100%;">
                <thead>
                    <tr>
                        <th>
                            Trucker Name
                        </th>
                        <th>
                            Destination
                        </th>
                        <th>
                            Status
                        </th>

                    </tr>
                </thead>
                <tbody>
                 <tr>
                     <th>
                         <select asp-for="Route.TruckerId" name="TruckerId" id="TruckerId">
                             @foreach (var item in Model.Truckers)
                             {
                                 <option value="@item.Id">@item.FirstName&nbsp;@item.LastName</option>
                             }
                         </select>
                     </th>
                     <th>
                         <select asp-for="Route.LocationId" name="LocationId" id="LocationId">
                             @foreach (var item in Model.Locations)
                             {
                                 <option value="@item.Id">@item.Name</option>
                             }
                         </select>
                     </th>
                    
                     <th>
                         <select asp-for="Route.StatusId" name="StatusId" id="StatusId">
                             @foreach (var item in Model.Statuses)
                             {
                                 <option value="@item.Id">@item.Name</option>
                             }
                         </select>
                     </th>
                   
                 </tr>
                </tbody>
                    
                    </table>

             
              
                <div class="form-group text-center">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
</form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>

TruckCompany.Web/Views/Routes/Delete.cshtml
@model RouteView

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Route</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.TruckerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TruckerName)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.LocationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LocationName)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusName)
        </dd>
    </dl>

    <form asp-action="DeletePost">
        <input name="DeleteId"type="hidden" asp-for="RouteNumber" />
        <input  type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-dark">Back to List</a>
    </form>
</div>

TruckCompany.Web/Views/Routes/Details.cshtml
@model RouteView

@{
    ViewData["Title"] = "Delete";
}

<h1>Details</h1>

<div>
    <h4>Trucker</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TruckerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TruckerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LocationName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LocationName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StatusName)
        </dd>
    </dl>

  
        <a asp-action="Index" class="btn btn-dark">Back to List</a>

</div>

TruckCompany.Web/Views/Routes/Index.cshtml
@model List<RouteView>
@{
    ViewData["Title"] = "Home Page";
}
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/v4-shims.css">
</head>
<body>
    <h1 class="display-4">Welcome</h1>

    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary" style="color:orange">Our Routes</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Routes" asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i>&nbsp;Add new Route</a>
        </div>
        <br /><br />
        @if (Model.Count > 0)
        {
            <table class="table table-bordered table-striped text-center" style="width:100%;">
                <thead>
                    <tr>
                        <th>
                           Trucker Name
                        </th>
                        <th>
                            Destination
                        </th>
                        <th>
                            Status
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(var item in Model)
                    {
                        <tr>
                            <td width="20%">@item.TruckerName</td>
                            <td width="20%">@item.LocationName</td>
                            <td width="20%">@item.StatusName</td>
                            <td width="50%">
                                <div>
                                    <a asp-controller="Routes" asp-action="Details" asp-route-Id="@item.RouteNumber" class="btn btn-info"><i class="fas fa-info"></i></a>
                                    <a asp-controller="Routes" asp-action="Update" asp-route-Id="@item.RouteNumber" class="btn btn-primary"><i class="fas fa-user-edit"></i></a>
                                    <a asp-controller="Routes" asp-action="Delete" asp-route-Id="@item.RouteNumber" class="btn btn-danger"><i class="fas fa-user-times"></i></a>
                                </div>
                                 

             
                                 
                          

                                       
                                  
  
                            </td> 
                        </tr>

                    }
                </tbody>
            </table>
        }
    </div>
</body>

TruckCompany.Web/Views/Routes/Update.cshtml
@model CreateModel

@{
    ViewData["Title"] = "Update";
}
<h1>Update</h1>

<h4>Route</h4>
<hr />
<div class="row">
    <div class="col-md-4 align-center">
        <form asp-action="Update">
            <input type="hidden" asp-for="Route.RouteNumber" />
            <table class="table table-bordered table-striped" style="width:100%;">
                <thead>
                    <tr>
                        <th>
                            Trucker Name
                        </th>
                        <th>
                            Destination
                        </th>
                        <th>
                            Status
                        </th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>
                            <select asp-for="Route.TruckerId" name="TruckerId" id="TruckerId">
                                @foreach (var item in Model.Truckers)
                                {
                                    <option value="@item.Id">@item.FirstName&nbsp;@item.LastName</option>
                                }
                            </select>
                        </th>
                        <th>
                            <select asp-for="Route.LocationId" name="LocationId" id="LocationId">
                                @foreach (var item in Model.Locations)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            </select>
                        </th>

                        <th>
                            <select asp-for="Route.StatusId" name="StatusId" id="StatusId">
                                @foreach (var item in Model.Statuses)
                                {
                                    <option value="@item.Id">@item.Name</option>
                                }
                            </select>
                        </th>

                    </tr>
                </tbody>

            </table>       
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-dark">Back to List</a>
</div>